### ISSUE TITLE
Lagging not working in standard shock capturing classes?

### ISSUE THREAD

**Issue by mfarthin** [erdc-cm/proteus#103]
I'm having trouble getting the shock-capturing classes to lag the numerical diffusion coefficient. Was this turned off on purpose (maybe for better robustness)?

Looking through the code, all of the calculateNumericalDiffusion routines set ```self.numDiff[ci]``` self.numDiff_last[ci] doesn't appear to be used as a 'right hand side' value anywhere.

**Comment by cekees** [comment]
closed by #283
