### ISSUE TITLE
problem with _ssl on new proteus Python build (OS X Mavericks)

### ISSUE THREAD

**Issue by malej** [erdc-cm/proteus#117]
Hey Guys,

I'm trying to build a clean proteus clone on my new Mac Pro (Mavericks) and I'm failing on a Python build in the import _ssl stage. I seem to to recall a similar issue when building on Garnet a while back, but I can't find any trace of it. Any idea?

```
[python] Building python/j7zqdigjptqs, follow log with:
[python]   tail -f /Users/malej/.hashdist/tmp/python-j7zqdigjptqs/build.log
[python|ERROR] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 1
[python|ERROR] command failed (code=1); raising
make: *** [/Users/malej/proteus/darwin/artifact.json] Error 127
[malej@matts-mac-pro] proteus (master) $ tail -f /Users/malej/.hashdist/tmp/python-j7zqdigjptqs/build.log
2014/09/02 12:20:25 - INFO: [package:run_job] import bz2
2014/09/02 12:20:25 - INFO: [package:run_job]     ok
2014/09/02 12:20:25 - INFO: [package:run_job] import hashlib
2014/09/02 12:20:25 - INFO: [package:run_job]     ok
2014/09/02 12:20:25 - INFO: [package:run_job] import _ssl
2014/09/02 12:20:25 - INFO: [package:run_job] Traceback (most recent call last):
2014/09/02 12:20:25 - INFO: [package:run_job]   File "<string>", line 1, in <module>
2014/09/02 12:20:25 - INFO: [package:run_job] ImportError: No module named _ssl
2014/09/02 12:20:25 - ERROR: [package:run_job] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 1
2014/09/02 12:20:25 - ERROR: [package:run_job] command failed (code=1); raising
```

**Comment by woodscn** [comment]
I had this same error with Yosemite. Possibly due to the R project gfortran (v4.2.3) I'm using, rather than home-brew. The specific failure in the log is 

"2015/04/22 12:57:34 - INFO: [package:run_job] checking whether Fortran 77 and C objects are compatible... no"

**Comment by ahmadia** [comment]
Do you have access to the homebrew compilers?  It is the only supported way
to build proteus on os x at the moment.

**Comment by woodscn** [comment]
Absolutely. I just didn't WANT to install an additional gfortran. Mostly I just saw the same error, and thought I'd throw up some additional information.

**Comment by cekees** [comment]
Closing this issue because it's really a hashstack-on-os x issue.
