### ISSUE TITLE
Proteus post-processing: time steps and variables

### ISSUE THREAD

**Issue by AlmostSurelyRob** [erdc-cm/proteus#191]
When I run Proteus I can get an xdf file which can be later opened in paraview. In paraview I seem to be able to visualise variable evolution with time, but I don't know exactly what I am visualising. I would prefer to visualise from python like you do in your notebooks, but I would still need the ability to get the value of the variables for particular time steps. Is it possible in the current code?

Currently I am doing something like
```python
x = ns.modelList[0].levelModelList[-1].mesh.nodeArray[:,0]
u = ns.modelList[0].levelModelList[-1].u[0].dof
pylab.plot(x[0:-1],u[0:-1:3])
pylab.show()
```
to visualise my Burgers 1D u variable. This will show only the last time step. Please let me know if it's possible to get earlier time steps too.

**Comment by mfarthin** [comment]
Right now, we usually go back and extract the solution from the hdf5 file where it's stored. An example of some simple code that we're using to reading back solution snapshots is in the `wip_add_deim` branch under the `test/POD/` directory. If you look at the `test_svd_space_res` function in `test_deim.py` you can see an example where we run a burgers equation and then go back and extract the solution snapshots from the xdmf archive and the corresponding hdf5 file. 

Please note that the code is just experimental right now for helping us explore nonlinear pod in proteus. In particular, that snapshot reading isn't going to work in parallel.

@tweigand, you may want to check this out too as an example for doing the parameter estimation.

**Comment by AlmostSurelyRob** [comment]
Thanks. This is great. It's convenient for me to actually read it from solution files. I can now recover the values from old time steps using the functions that I found in the directory. Can you just comment on two more things?

 1. How can I get the time step value. Paraview clearly knows the time associated with the data. How can I recover it from xdmf?
 1. What is the meaning of the columns

For instance now I am doing something like this
```python
archive = Archiver.XdmfArchive(".", "burgers_kl_1d", readOnly=True)
label_base = "/{0:s}{1:d}"

# How to get a time step sequence?
u1 = read_from_hdf5(archive.hdfFile, label_base.format("u", 400))
u2 = read_from_hdf5(archive.hdfFile, label_base.format("u", 719))

# Why third column is so smooth? What is the meaning of the columns?
plt.plot(u1[0:-1:3])
plt.plot(u2[0:-1:3])
plt.show()
```
I am not worried about parallel at the moment. My post-processing will be definitely a single-processor, single-core adventure.

**Comment by cekees** [comment]
Here's an example of how to get the actual time step sequence:
```Python
for n,Time in enumerate(archive.tree.getroot().iter("Time")):
    print "t_n = ",Time.attrib['Value'],"\nn   = ",`n`
```

**Comment by cekees** [comment]
OK, that wasn't quite write because we write two grid  collections.  Here's a loop and plot commands for just  the dgp1 part

```
%matplotlib inline
import  matplotlib.pyplot  as plt
fig,ax = plt.subplots()
for a in archive.tree.getroot().iter("Grid"):
    if a.attrib['GridType'] == "Collection":
        if a.attrib['Name'] == "Mesh_dgp1_Lagrange":
            for n,Time in enumerate(a.iter("Time")):
                u = archive.hdfFile.getNode("/u0"+`n`)
                fig,ax = plt.subplots()
                ax.plot(u)
                plt.savefig("u%03d.png" % (n,))
                plt.clf()
```

**Comment by AlmostSurelyRob** [comment]
Thanks a lot. That allowed me to get exactly what I wanted. I'll send you a stub of my presentation later on today.

```python
    # Extract the number of time steps
    # Apparently Proteus creates a collection of grids
    M = 0
    for a in archive.tree.getroot().iter("Grid"):
        if a.attrib['GridType'] == "Collection":
            if a.attrib['Name'] == "Mesh_dgp2_Lagrange":
                Time = list(enumerate(a.iter("Time")))
                M = len(Time)
```
and in another place I could plot solutions for the time steps I wanted so I am all good. I started writing a little presentation about this.
