### ISSUE TITLE
Can't build petsc

### ISSUE THREAD

**Issue by ernstameese** [erdc-cm/proteus#196]
Trying to build proteus under SUSE Linux I get the following message in the log file:

2015/01/16 17:35:15 - INFO: [package:run_job] *******************************************************************************
2015/01/16 17:35:15 - INFO: [package:run_job]          UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
2015/01/16 17:35:15 - INFO: [package:run_job] -------------------------------------------------------------------------------
2015/01/16 17:35:15 - INFO: [package:run_job] The BLAS/LAPACK libraries -llapack -lblas -Wl,-rpath,/home/cranfield/.hashdist/bld/patchelf/k3rloj265ogt/lib -L/home/cranfield/.hashdist/bld/patchelf/k3rloj265ogt/lib -Wl,-rpath,/home/cranfield/.hashdist/bld/mpi/hbd47qrzmwye/lib -L/home/cranfield/.hashdist/bld/mpi/hbd47qrzmwye/lib -Wl,-rpath,/usr/lib64/gcc/x86_64-suse-linux/4.7 -L/usr/lib64/gcc/x86_64-suse-linux/4.7 -Wl,-rpath,/usr/x86_64-suse-linux/lib -L/usr/x86_64-suse-linux/lib -lmpichf90 -lgfortran -lm -lgfortran -lm -lquadmath -lm
2015/01/16 17:35:15 - INFO: [package:run_job] cannot used with a shared library
2015/01/16 17:35:15 - INFO: [package:run_job] Either run ./configure with --with-shared-libraries=0 or use a different BLAS/LAPACK library
2015/01/16 17:35:15 - INFO: [package:run_job] *******************************************************************************

I have installed lapack, but that does not seem to change anything.  Do you have any suggestion for how to proceed?

**Comment by ahmadia** [comment]
Looks like there is a problem with the system BLAS/LAPACK on SUSE.  You can modify the hashstack file to not use the system lapack.

**Comment by ahmadia** [comment]
First can you try:

```
sudo yum install lapack-devel
```

And then re-run?  We could also try having your PETSc install its own BLAS/LAPACK

**Comment by ahmadia** [comment]
@ernstameese - Let me know if the above suggestions don't work, I am happy to iterate with you on this.

**Comment by ernstameese** [comment]
Hi Aron,

Thank your for impressively quick response.  I have already installed lapack-devel using

sudo zypper install lapack-devel

You suggest in your previous e-mail that I modify the hashstack file to not use system lapack.  I am new to HashDist, so some guidance as to how to do this would be very nice.

Regards,
Ernst

___________________________________________
dr.ing. Ernst A. Meese, Senior Research Scientist
SINTEF Materials and Chemistry
Sector of Oil and Gas Process Technology
Department for Flow Technology

Visiting Scientist at Cranfield University
Visiting address               : Whittle Building, Room 275
English phone                   : +44 (0) 7914 847889
Norwegian phone          : +47 98 28 38 98

**Comment by ahmadia** [comment]
Hi Ernst.  

Let's try this option.  Go ahead and modify the file: `stack/examples/proteus.linux2.yaml` so that the PETSc section looks like this:

```
  petsc:
    build_with: |
      parmetis
    download: |
      fblaslapack, superlu, superlu_dist, spooles, hypre, blacs, scalapack, mumps
    coptflags: -O2
    link: shared
    debug: false
```

Here, we've added fblaslapack to the PETSc download options, so it should be able to install a suitably configured BLAS/LAPACK.  It won't be particularly fast, but Proteus doesn't really use this LAPACK, so I think this should work.  

If you provide the exact version of SuSE you're trying to build on I can try and give you more specific instructions on how to fix this.

Let me know how it goes.

**Comment by ernstameese** [comment]
Hei Aron,

That worked.  Proteus is now compiled and the make check went through.  Thank you.

Regards,
Ernst

**Comment by ahmadia** [comment]
That's excellent news.
