### ISSUE TITLE
Cannot create a custom rectangular domain

### ISSUE THREAD

**Issue by robertsawko** [erdc-cm/proteus#199]
Hello,

I am trying to setup a rectangular domain where y in (-4,4) and I run into some difficulties. After going through DomainTutorial notebook I believe that the following should work:

```python
#kinetic.py
import proteus.default_p as p
...
# p.nd = 2
# p.L = (2 * np.pi, 8)
# p.x = (0, -4)  # This doesn't seem to affect NumericalSolution
# Now trying to be more explcit about domain
p.domain = Domain.RectangularDomain(L=(2 * np.pi, 8), x=(0, -4), name=p.name)
...
ns = NumericalSolution.NS_base(so, [p], [n], so.sList, opts)
ns.calculateSolution("kinetic")
```

I looked up a couple of files so I understand that `default_p.domain = None` and I noticed that `NumericalSolution.py` has
```python
            if p.domain == None:
                if p.nd == 1:
                    p.domain = Domain.RectangularDomain(L=p.L[:1],name=p.name)
                elif p.nd == 2:
                    if p.polyfile != None:
                        p.domain = Domain.PlanarStraightLineGraphDomain(fileprefix=p.polyfile,name=p.polyfile)
                    else:
                        p.domain = Domain.RectangularDomain(L=p.L[:2],name=p.name)
                elif p.nd == 3:
                    if p.polyfile != None:
                        p.domain = Domain.PiecewiseLinearComplexDomain(fileprefix=p.polyfile,name=p.polyfile)
                    elif p.meshfile != None:
                        p.domain = Domain.Mesh3DMDomain(p.meshfile)
                    else:
                        p.domain = Domain.RectangularDomain(L=p.L[:3],name=p.name)
                else:
                    raise RuntimeError("No support for domains in more than three dimensions")
```

The file contains also the numerical and physics setup. I just run it with `python2 kinetic.py`. In the current form I get
```
[       0] *** Global ***
Number of triangles  : 800
Number of edges : 1240
Number of nodes : 441

*** Local ***
Number of triangles  : 800
Number of edges : 1240
Number of nodes : 441

[       0] Setting up MultilevelTransport for kinetic
[       0] Building Transport for each mesh
[       0] Generating Trial Space
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see http://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind[0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[0]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run
[0]PETSC ERROR: to get more information on the crash.
application called MPI_Abort(MPI_COMM_WORLD, 59) - process 0
```
If I uncomment `p.nd` and `p.L` lines the code will run, even though i believe I am doing exactly the same! Clearly there's something I am missing. Please let me know.

**Comment by cekees** [comment]
I'm not sure what is going on here.  When you leave  domain=None proteus  is actually just using `L` (not the offset  `x`), so the  two domain's aren't equivalent.  I suspect when you switch to your offset domain that it's hitting a problem in your boundary condition setter functions that aren't being triggered by the domain with lower left corner (0,0).

**Comment by cekees** [comment]
To be clear, the code path where you just set L and x looks like a bug in proteus or at  least something that  should be made consistent with the behavior of RectangularDomain. It seems like a bad idea  for proteus to ignore the offset `x`.

**Comment by cekees** [comment]
So let's leave this open, but I'd suggest that you try debugging your new version with RectangularDomain.  You could put a print statement in your boundary condition setters to try to track the values of  `x` they are being called  on and see if the segv is generated there.

**Comment by AlmostSurelyRob** [comment]
Ok. Thanks. I'll do that for now. I was aware that `p.x = (0.0, -4.0)` will not do anything, but I left it out to show an alternative way that it could be made consistent with RectangularDomain. I thought about BC but the BC code I've got only accounts for the direction that was not shifted so I dropped that. I'll do some debugging now and see how it goes.

**Comment by AlmostSurelyRob** [comment]
I corrected my BC code. I didn't change anything to the periodic part as I want to have periodicity in x and 0 value for y direction. The problem went away.

```python
def dirichletZeroBC(x, flag):
    a = x[1]
    print "zeroBC: ", x
    if np.abs(a) == 4:
        return 0

p.dirichletConditions = dict((i, dirichletZeroBC) for i in range(2))
p.advectiveFluxBoundaryConditions = dict((i, emptyBC) for i in range(2))
p.diffusiveFluxBoundaryConditions = dict((i, {}) for i in range(2))


def getPBC(x, flag):
    eps = 1.0e-8
    print "periodicBC", x
    if x[0] < eps or x[0] >= p.L[0] - eps:
        return np.array([0.0, 0.0, 0.0])

p.periodicDirichletConditions = dict((i, getPBC) for i in range(2))
```
This is still not quite correct for my case as the first variable is probably not fixed value, but I need to go back to the theory to verify this. It's irrelevant to this issue. The problem is closed for me. Before my BC code was empty for `p.dirichletConditions` so perhaps there was something default that was crashing the shifted rectangle.
