### ISSUE TITLE
Data transfer and others...

### ISSUE THREAD

**Issue by adimako** [erdc-cm/proteus#201]

**Comment by ahmadia** [comment]
> Gauges: I am running now Aron's functions with quiescent water to see differences from before. Eleni will run some intial wave cases with both the function probes and keeping paraview output to do a second check. If it is ok, we will start using them, without archiving so many datafiles.

Make sure you're using https://github.com/erdc-cm/proteus/pull/195 at as recent as you can.  Note that I just changed the factory function from LineGauge to LineIntegralGauge to make room for the new LineGauge factory function.
