### ISSUE TITLE
Docs won't build unless PROTEUS environment variables is set

### ISSUE THREAD

**Issue by woodscn** [erdc-cm/proteus#243]
OS X, clean install, homebrew tools. 

In proteus directory (as per the install instructions) run make; make check. 

In proteus/docs run make html. 

Yields the following:

Warning: tag INPUT: input source `/proteus' does not exist
error: tag OUTPUT_DIRECTORY: Output directory `/doc/build/html/capi' does not exist and cannot be created
Exiting...

export PROTEUS=.. appears to fix the problem. Perhaps PROTEUS is meant to be set in the initial build?

**Comment by cekees** [comment]
Thanks, you're correct. If you run `make doc` from the proteus root directory then it sets PROTEUS for you. It also looks like I pushed some changes to the docs  that required `pip  install  sphinx-bootstrap-theme`.   The static version of the docs are available here https://proteus.usace.army.mil, but you will probably get a warning about the certificates unless you install the DoD certs. The are supposed  to be at http://proteus.usace.army.mil, but there appears to be a problem with the proxy server. I'm in the process  of getting the docs updated etc.

**Comment by woodscn** [comment]
Yep, works as advertised. It might be nice to add a line about make doc to the install instructions.

As for the static site, http gives the following error:

Network Error (gateway_error) 

An error occurred attempting to communicate with an HTTP or SOCKS gateway.
The gateway may be temporarily unavailable, or there could be a network problem.

For assistance, contact your network support team.

If I manually change that for https, then I have no problems (I guess the DoD certs must be installed by default for Safari in OS X).
