### ISSUE TITLE
Python compilation crashed due to lack of ssl

### ISSUE THREAD

**Issue by robertsawko** [erdc-cm/proteus#340]
Hello,

This time I am compiling Proteus on Ubuntu 12.04. Hashdist break after compiling python and testing for its
```
PROTEUS          : /home/robert/projects/proteus
PROTEUS_ARCH     : linux2
PROTEUS_PREFIX   : /home/robert/projects/proteus/linux2
PROTEUS_VERSION  : 72aa6baa7e13f258c2dfa9497a8801bd79bb0cc9
HASHDIST_VERSION : 71d335be9ee04e3cc9a9df92a9348a2d8e3ed607
HASHSTACK_VERSION: ed55f4e10f07eb0b85fa6a0d15f4d0e5104902c0
 ```

And the line it breaks
```
[python] ImportError: No module named _ssl
[python|ERROR] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 1
[python|ERROR] command failed (code=1); raising
```

The ssl import is a part of testing clearly visible in yaml file. Please let me know if you have any ideas how to fix it.

**Comment by cekees** [comment]
I'm guessing it's because you don't have `libssl-dev` installed. That hashstack version tries to use the host version of openssl. You could either install it with `apt-get install libssl-dev` or you could switch the default.yaml to be

`openssl:` 
(delete the next line `use: host-ssl`)

**Comment by robertsawko** [comment]
Yep, that was it. Thanks for a quick response.
