### ISSUE TITLE
petsc compilation breaks over a copy command

### ISSUE THREAD

**Issue by robertsawko** [erdc-cm/proteus#342]
I really hope that you don't mind me posting every single issue with proteus+hashdist compilation issue here. I do treat it as my diary almost.

On Ubuntu 12.04 I came across the following error
```
cp: cannot create regular file '/home/robert/.hashdist/bld/petsc/yzkrdowxhpu4/lib/': Not a directory
```
This looks strange as indeed the directory `petsc` in `bld` doesn't yet exist as this is the package which is being compiled. I have some `petsc` files in `tmp`.

**Comment by cekees** [comment]
I believe we saw this recently. Could you try disabling superlu_dist  and superlu in the petsc build? I seem to recall that the problem comes up when petsc  tries to install external packages.

**Comment by robertsawko** [comment]
Sorry, I am not being very resourceful. The problem is that I cannot find superlu in the configure step. petsc is compiled with a companion Python script `petsc.py` which, I understand, sets up configure options with some architecture based conditions. This script doesn't mention superlu or superlu_dist. With `--with-superlu=0` hashdist still attempts to compile superlu.

Where can I find a s configure step that is actually being executed?

**Comment by robertsawko** [comment]
Is there a way to see the actual `./configure` command with all the options in hashdist? Something like a hashdist debug mode.

**Comment by cekees** [comment]
Yes, go into proteus/stack and run `../hashdist/bin/hit build default.yaml --debug`

**Comment by robertsawko** [comment]
Success!

Limited, but success nevertheless.

The debug command is extremely powerful, thanks for a clarifying email. I've done this

```
cd stack
../hashdist/bin/hit build default.yam --debug -v
vim _hashdist/build.sh
# Take out the download stuff for superlu
/bin/bash _hashdist/build.sh
```
And it compiles now. I am now trying to figure out why the configure script gets generated with superlu download set to 1.

**Comment by robertsawko** [comment]
There's no easy way out of this. I think I went through all the stack now, but proteus does depend on superlu. Just got a linker error

```
gcc -pthread -shared -L/home/robert/.hashdist/bld/bzip2/x77hkrpcbch3/lib -Wl,-rpath=/home/robert/.hashdist/bld/bzip2/x77hkrpcbch3/lib -L/home/robert/.hashdist/bld/gdbm/ckkq7rf2zcin/lib -Wl,-rpath=/home/robert/.hashdist/bld/gdbm/ckkq7rf2zcin/lib -L/home/robert/.hashdist/bld/launcher/wvmh5uvayzv3/lib -Wl,-rpath=/home/robert/.hashdist/bld/launcher/wvmh5uvayzv3/lib -L/home/robert/.hashdist/bld/ncurses/26ibjcbdg7jr/lib -Wl,-rpath=/home/robert/.hashdist/bld/ncurses/26ibjcbdg7jr/lib -L/home/robert/.hashdist/bld/openssl/nnqbgp4kemir/lib -Wl,-rpath=/home/robert/.hashdist/bld/openssl/nnqbgp4kemir/lib -L/home/robert/.hashdist/bld/patchelf/k3rloj265ogt/lib -Wl,-rpath=/home/robert/.hashdist/bld/patchelf/k3rloj265ogt/lib -L/home/robert/.hashdist/bld/readline/luebmteyyxdv/lib -Wl,-rpath=/home/robert/.hashdist/bld/readline/luebmteyyxdv/lib -L/home/robert/.hashdist/bld/sqlite/7gd4urmeii3r/lib -Wl,-rpath=/home/robert/.hashdist/bld/sqlite/7gd4urmeii3r/lib -L/home/robert/.hashdist/bld/zlib/v6anirfvk2op/lib -Wl,-rpath=/home/robert/.hashdist/bld/zlib/v6anirfvk2op/lib -Wl,-rpath,/home/robert/.hashdist/bld/python/hinzjjpeqn5l/lib build/temp.linux-x86_64-2.7/proteus/superluWrappersModule.o -L/home/robert/projects/proteus/linux2/lib -L. -L. -L/home/robert/.hashdist/bld/python/hinzjjpeqn5l/lib -lm -lsuperlu_4.3 -llapack -lblas -lpython2.7 -o build/lib.linux-x86_64-2.7/proteus/superluWrappers.so -lblas -Wl,-rpath,/home/robert/projects/proteus/linux2/lib
/usr/bin/ld: cannot find -lsuperlu_4.3
```
So I think we need to fix superlu compilation alongside petsc rather than just switch it off.

**Comment by cekees** [comment]
That's right. You can still have `superlu:` in default.yaml, just don't
have anything about superlu in the 'petsc:' section.

**Comment by robertsawko** [comment]
Right, great... I found superlu in default.yaml. Kind of an obvious place. There was a download section in petsc and it was listed there. I don't know how I missed it.

I have now edited the default yaml and also PROTEUS_SUPERLU_LIB in `proteus/config/default.py` to version 4.1 as it wanted 4.3. It occurred to me now, that I should have edited superlu.yaml to get the newer version. For now it's compiling proteus. If it succeeds I will retry with 4.3.

**Comment by robertsawko** [comment]
Yep. Now I have a working compilation with superlu 4.3, although I need to as for one more clarification.

Why is superlu pointing to your own fork of superlu? It seems like a blend between 4.3 and 4.1.

**Comment by cekees** [comment]
At some point (probably prior to hashdist) we had to make some modifications to build it as a proteus dependency, and I haven't yet tried to set up a build directly from the superlu tarball from the developers. Just haven't gotten around to it.
