### ISSUE TITLE
curl compilation breaks

### ISSUE THREAD

**Issue by robertsawko** [erdc-cm/proteus#343]
So I am trying to run a parallel compilation on my personal Arch linux OS and unfortunately I get stuck on different issues. I already followed the comments and patches by @tridelat from #327, but now I break on curl with a linking error

```
[curl] libtool: link: gcc -O2 -Wno-system-headers -Wl,-rpath=/home/robert/.hashdist/bld/libidn/mcbrsf3bkfkq/lib -Wl,-rpath=/home/robert/.hashdist/bld/openssl/nnqbgp4kemir/lib -Wl,-rpath=/home/robert/.hashdist/bld/patchelf/k3rloj265ogt/lib -Wl,-rpath=/home/robert/.hashdist/bld/zlib/v6anirfvk2op/lib -o .libs/curl curl-tool_binmode.o curl-tool_bname.o curl-tool_cb_dbg.o curl-tool_cb_hdr.o curl-tool_cb_prg.o curl-tool_cb_rea.o curl-tool_cb_see.o curl-tool_cb_wrt.o curl-tool_cfgable.o curl-tool_convert.o curl-tool_dirhie.o curl-tool_doswin.o curl-tool_easysrc.o curl-tool_formparse.o curl-tool_getparam.o curl-tool_getpass.o curl-tool_help.o curl-tool_helpers.o curl-tool_homedir.o curl-tool_hugehelp.o curl-tool_libinfo.o curl-tool_main.o curl-tool_metalink.o curl-tool_mfiles.o curl-tool_msgs.o curl-tool_operate.o curl-tool_operhlp.o curl-tool_panykey.o curl-tool_paramhlp.o curl-tool_parsecfg.o curl-tool_setopt.o curl-tool_sleep.o curl-tool_urlglob.o curl-tool_util.o curl-tool_vms.o curl-tool_writeenv.o curl-tool_writeout.o curl-tool_xattr.o ../lib/curl-strtoofft.o ../lib/curl-strdup.o ../lib/curl-rawstr.o ../lib/curl-nonblock.o ../lib/curl-warnless.o  -L/home/robert/.hashdist/bld/libidn/mcbrsf3bkfkq/lib -L/home/robert/.hashdist/bld/openssl/nnqbgp4kemir/lib -L/home/robert/.hashdist/bld/patchelf/k3rloj265ogt/lib -L/home/robert/.hashdist/bld/zlib/v6anirfvk2op/lib ../lib/.libs/libcurl.so -lz -Wl,-rpath -Wl,/home/robert/.hashdist/bld/curl/dvprpozh3php/lib
[curl] ../lib/.libs/libcurl.so: undefined reference to `SSLv3_client_method'
```

I already tried a few work-arounds, by configuring with no ssl, but that didn't help and I don't think it's what we would like in the long run.

**Comment by cekees** [comment]
Can you do `nm /home/robert/.hashdist/bld/openssl/nnqbgp4kemir/lib/*.so | grep SSLv3_client_method`?

**Comment by robertsawko** [comment]
Sure, I can, but it seems that the directory doesn't exist at all. I've

```
ls home/robert/.hashdist/bld/openssl/nnqbgp4kemir
artifact.json  build.json  build.log.gz  id
```

When I remove openssl to force hashdist to recompile it will casually mention it's a "virtual package".

**Comment by cekees** [comment]
OK, if ssl is a host package then you may need  to make sure something like libssl-dev is installed like we did on ubuntu.

**Comment by robertsawko** [comment]
I think I've got that. Arch usually doesn't differentiate between ordinary and dev packages and the header files are bundled with the main package. I cross-validated with my Ubuntu installation and I've got all the header file and all the so file from Ubuntu, even more.

My fear is that there's something different about the library from the host.

**Comment by cekees** [comment]
OK, try running `nm /usr/lib/*ssl*.so | grep SSLv3_client_method` to see if they missing method is defined somewhere in your system ssl.  Have you tried building with the hashdist openssl (i.e. just removing the `use: host-openssl` line)?

**Comment by robertsawko** [comment]
I see. `nm` seems really useful. Nope I don't have these symbols on Arch. Ubuntu by comparison doesn't let me query `libssl.so` and replies with `no symbols`. The `libssl.a` though on Ubuntu contains `SSLv3_server_method`.

**Comment by cekees** [comment]
Is it possible that the package  name on Arch is  actually something like openssl rather than libssl?

**Comment by robertsawko** [comment]
This is exactly the case. But as I said, it's installed and it seems to contain most of the files in Ubuntu libssl-dev.

**Comment by cekees** [comment]
OK, at this point I think it might be best to try letting hashdist build openssl within the stack.

**Comment by robertsawko** [comment]
Ok. I just switched of openssl-host from `default.yaml` and it went like a charm.
