### ISSUE TITLE
Future development tasks for HRW team

### ISSUE THREAD

**Issue by adimako** [erdc-cm/proteus#362]
@cekees, @tridelat have a look at these and  feel free to add more
- Cythonize BC module (Tristan reported 10-20% computational overhead by just using the absorption zone, where no sine calculation is performed)
- Tag a code version? (I think we are almost there)
- Keep up development:
  - e.g. waveTools (optimise and add 2nd order correction, ramping functions etc)
- .... others

**Comment by tridelat** [comment]
- https://github.com/erdc-cm/proteus/pull/455
- https://github.com/erdc-cm/proteus/releases/tag/1.3.3
- https://github.com/erdc-cm/proteus/pull/471 https://github.com/erdc-cm/proteus/pull/492
