### ISSUE TITLE
Documentation Dependency - sphinxtogithub

### ISSUE THREAD

**Issue by alistairbntl** [erdc-cm/proteus#378]
I received a 'module error cannot find sphinxtogithub' when running `make doc`.  After installing sphinxtogithub the documentation then compiled.  Should this be added to the build stack?  Better still, I found the following :

https://github.com/blog/572-bypassing-jekyll-on-github-pages

which suggests the sphinxtogithub script is unnecessary.  I'd be happy to fix this but wanted feedback on the preferred approach to take.

**Comment by alistairbntl** [comment]
@cekees - did this get resolved by your PR on the doc branch?

**Comment by cekees** [comment]
It should have. I removed the sphinxtogithub extension from `doc/source/conf.py`, and I think that's the only way it comes in. I added the .nojekyll file to the gh-pages branch.
