### ISSUE TITLE
Establishing a Documentation Standard for Proteus

### ISSUE THREAD

**Issue by alistairbntl** [erdc-cm/proteus#384]
I'd like to start a discussion about establishing a set of documentation standards for Proteus.

In general I believe a documentation standard would improve coding efficiency (especially for newcomers like myself) and support wider spread adoption of the Proteus library.  It seems to me that all new patches and features added to the library should adhere to this standard, while overtime we could work towards incorporating this standard into some of the less documented parts of the code base.

There are two established standards that would be easy to adopt - the Google standard and the numpy standard.  For a description of these see https://sphinxcontrib-napoleon.readthedocs.io/en/latest/ (thanks @tridelat ).

Since parts of the Proteus library require detailed documentation, I am inclined to believe the numpy standard is a natural choice.  If we choose to adopt the numpy standard we would also need a package that supports Sphinx rendering.  Two options include Napoleon (see link above) or numpydoc (https://github.com/numpy/numpydoc).

These are just some initial thoughts and I'm curious whether other people agree this is a worthwhile direction to go in.  In particular what do you think @cekees , @mfarthin , @tridelat  and @adimako ?

**Comment by cekees** [comment]
I see, Napolean and numpydoc  help you write docstrings in a simpler  text style  while still rendering nicely with sphinx. I'll have to look into the pros and cons of numpy versus Google standards and Napolean vs numpydoc to fix the sphinx rendering.

**Comment by tridelat** [comment]
Napoleon comes packaged with sphinx from version 1.3 (https://github.com/sphinx-doc/sphinx/tree/master/sphinx/ext/napoleon) and can parse both numpy and Google standards.

**Comment by alistairbntl** [comment]
Cool, so if I understand your e-mail @cekees correctly, it seems that jupyter notebooks will be able to support converting numpy documentation into nicely rendered html soon.
If this is correct, I vote to move forward with numpy as the standard.   This can always change in the future, but its been tried and tested in a scientific setting so I think its a good fit.
As for Napoleon vs. numpydoc, I need to try regenerating the documentation with both before forming an opinion.  I will say that @tridelat brings up a good point, so unless numpydoc appears significantly better in sphinx, I'd be inclined to go with Napoleon.

**Comment by cekees** [comment]
I tested it. Booth google and numpy conventions yield identical output from sphinx.  Numpy is probably more readable text for what we do. I vote we move forward with numpy but accept  google. I don't think there's a strong reason to be strict about it since it only shows up in the text form of the documentation. They teach the google style on kahn academy so we may start to get people for whom writing the google style is comfortable, and I'd rather encourage any good  documentation that worry about consistency at the text level.

**Comment by alistairbntl** [comment]
I think that makes a lot of sense. :+1:

**Comment by alistairbntl** [comment]
After merging #390 I think this issue can be closed...
