### ISSUE TITLE
Regression in quad_tests.py

### ISSUE THREAD

**Issue by alistairbntl** [erdc-cm/proteus#388]
There has been a regression in one of the quad_tests. 
@cekees : it looks like the problem is that a `p_` term is being dropped from some of the names, for example `nodeMaterialTypes_p_t0` has become `nodeMaterialTypes_t0`.  Is this related to a change you made in one of your .xmf PRs?  If so, the output still looks okay so I think I can just update the file to reflect the new naming convention.

**Comment by alistairbntl** [comment]
#410 fixes this bug.  Will close once merged.

**Comment by zhang-alvin** [comment]
@alistairbntl has this been resolved? If so could you point to the PR hash?

**Comment by alistairbntl** [comment]
Thanks @zhang-alvin .  This issue has been resolved.  
I'm not sure what the PR hash is, but the tests in question can be found in `proteus/tests/mesh_tests` on the master branch (current hash c23d577) and are all passing.
