### ISSUE TITLE
C warning/error messages and logEvent

### ISSUE THREAD

**Issue by nerisaurus** [erdc-cm/proteus#424]
Is there framework available to pass C code based error messages/log information to the standard tools used for logging results?  For instance, proteus/mprans/RANS2P.h has a call:

`std::cerr<<"warning, diffusion term with no boundary condition set, setting diffusive flux to 0.0"<<std::endl;`

on line 1534.  This is a warning that the code wants to inform the user about in order to potentially fix the boundary conditions of their model.  It is not included in any logs (even with -l10), though, and requires the user to see it when it flashes by in output.  

It also seems more prone to race conditions on printing out the results, leading to garbled messages in parallel processing - I'm not sure if the standard log has a strategy to avoid race conditions or if I've just been lucky in not seeing any, but that may be another advantage to wrapping these warnings into the main logging tools.

**Comment by zhang-alvin** [comment]
This issue is effectively the same as #3. I'll close this for now and work directly off the initial issue.
