### ISSUE TITLE
Another Installing error on stampede

### ISSUE THREAD

**Issue by yuxianglin** [erdc-cm/proteus#462]
Hi,

I have another issue regarding to the installation of proteus in Stampede as shown in the screenshot, which says cannot configure with given option when installing f2cblaslapack. I am wondering why it would have such dependency in default.yaml while my linux machine does not. Any advise would be appreciated. 

![screenshot from 2016-11-01 18-43-22](https://cloud.githubusercontent.com/assets/17280119/20071917/07782690-a4ec-11e6-8bf3-a4187c034702.png)

**Comment by cekees** [comment]
It shouldn't need f2cblaslapack in the profile, but it may be trying to
build it  because petsc is not recognizing the blas and lapack library on
stampede that the stack was originally configured with.  You could use the
openblas in hashstack if we can't figure out how to link to the vendor blas
on stampede.

**Comment by yuxianglin** [comment]
Hi Chris:

Thank you for your quick reply.

How to to use the openblas in the hashstack? You mean to replace f2cblaslapack to openblas in default.yaml?

**Comment by cekees** [comment]
Yes, you'd want to modify it to be something like

```
blas:
  use: openblas
lapack:
  use: openblas
petsc:
 #(just  don't specify anything about blas or lapack here)
```
Take a look at some of the other proteus profiles in proteus/stack/examples/proteus.*.yaml to see how blas and lapack are configured on various platforms.

**Comment by yuxianglin** [comment]
Hi Chris:

Thank you for your clarification.

I used above configuration, but the code did not find the lapack library. The I was sugguested by Steven to modified the f2cblaslapack to fblaslapack, then proteus successfully built. However by make check It still lack the lapack.so by saying _import superluWrappers, ImportError: liblapack.so: cannot open shared object file: No such file or directory._ 

Is it because we fail to specify the lapack dependencies in default.yaml?(specifying openblas is not working)

Yuxiang

**Comment by cekees** [comment]
OK, that's good, you're almost  there. Look in the proteus/linux2 or  proteus/stampede directory in the lib subdirectory  and make sure liblapack.so is there. Do `pwd` to print your path to  the lib  dir. If it is then do  something like this 

```
export  LD_LIBRARY_PATH=your_path_to_the_lib_dir:${LD_LIBRARY_PATH}
````

Then try make check.

**Comment by yuxianglin** [comment]
Great, it works, finally.

Thank you very much for your recent assistance, Chris.

**Comment by cekees** [comment]
OK, great. The "proper" way to avoid that  runtime link error is to modify https://github.com/erdc-cm/proteus/blob/master/proteus/config/stampede.py to point to the blas you are  using. Looks  like the current stampede config points to openblas. 

Also, you may want to go ahead  and create branches and commit your changes to both proteus and hashstack like this:

```
cd your_proteus
git checkout -b stampede_fixes
git commit -a
cd  stack
git checkout -b stampede_fixes
git  commit -a
```

You can decide later whether it's  worth doing a pull request to either proteus or stampede as those commands above will just create a local branch .

Thanks for your patience working through the build issues.
