### ISSUE TITLE
[BUG] WaveTools latest changes

### ISSUE THREAD

**Issue by tridelat** [erdc-cm/proteus#475]
@adimako the latest changes to `WaveTools` have introduced a bug where the velocity profile of the waves is not correct (77e6444f08ca36f29b6c955719b3e2f9b0260196). For example, a linear wave with `period=1.`, `mwl=water_depth=1.5`, `height=0.07` will give increasingly high velocities passed a certain depth in the water column.
I also get an OOM error on copper after a while when using `WaveTools` (the error comes faster when using `Fenton` than when using `Linear` waves), I am not sure if it is related to this bug or a separate memory leak.

**Comment by tridelat** [comment]
@adimako, the velocity profiles are mostly fine with 11a46843cc0fcf, but velocities are sharply cut for `d>=lambda/2` for `MonochromaticWaves`.
It did not solve the OOM error problem unfortunately.

**Comment by tridelat** [comment]
@adimako reverting to fd76cd3b4084d93d9e76f95275344488d2710a17 for `WaveTools` (so only the `WaveTools.pyx` file, the rest of proteus on the latest master), the velocity profiles of the waves are different (no cut or increase in velocity for the conditions in the first message above), and it solves the OOM error.
Reverting to the old version is much much slower however, which is expected (4.5+ times slower than the cythonised version for a test case I am running)

**Comment by adimako** [comment]
@tridelal I do not mind so much the velocity profile, as we can always increase the accuracy of the Taylor approximation possibly to reach lamda = d with acceptable accuracy. The OOM may come from that I am not deallocating memory after function calls. I presume that class is only called once in BC module and not every timestep, so that leaves us with the functions leaking memory. Let me check

**Comment by tridelat** [comment]
The issues with `WaveTools` have now been tackled:
  - **OOM error**: the updates to `WaveTools` that were merged in Proteus 1.2 got rid of the OOM error.
  - **Velocity profile**: The velocity profile can be recovered for the whole water column by using `cosh` and `sinh` instead of `fastcosh` and `fastsinh` at the cost of computational power.
  - **Pressure spikes**: Using `sinh` and `cosh` gets rids of pressure spikes that could be encountered when the time step is fine due to approximations of `fastcosh` and `fastsinh` ( @cekees @manuel-quezada )
  - **Water inflow**: Stokes drift velocity that caused the global water level to go up for nonlinear waves can be corrected by subtracting a relevant average velocity from the seabed to the mean water level across the boundary (new addition that has not been pushed to Proteus yet, under test right now with encouraging results).

Also, using `cosh` and `sinh` instead of the fast version gives exactly the same results as the old version `WaveTools` for monochromatic waves. Closing.
