### ISSUE TITLE
hydrostatic outflow boundary conditions missing in mprans.BoundaryConditions

### ISSUE THREAD

**Issue by cekees** [erdc-cm/proteus#531]

**Comment by cekees** [comment]
I think we fixed this. @Giovanni-Cozzuto-1989 and @tridelat could you check that hydrostatic outflow conditions work reasonably well without sponge layers?

**Comment by Giovanni-Cozzuto-1989** [comment]
I think this works fine.
I did a test of a simple tank with current and the outlet seems to be stable.
(This without any turbulence model of course).

**Comment by cekees** [comment]
Thanks!
