### ISSUE TITLE
Scorec compilation fails in hydra

### ISSUE THREAD

**Issue by adimako** [erdc-cm/proteus#566]
We get a "cannot find aph.h" error. I think @tridelat has solved this already? Any advice from @zhang-alvin would be appreciated as well.

**Comment by zhang-alvin** [comment]
Can you post the branch commit and the stack commit? You would normally find the `apf.h` header file in the `proteus/$PROTEUS_ARCH/include` (e.g. proteus/linux2/include) directory. You can check if the missing files are there first.

**Comment by adimako** [comment]
@zhang-alvin. It is not there. I think it is a stack problem. This file is not at the PROTEUS_ARCH and not in my stack as well. Where is it coming from?

**Comment by adimako** [comment]
It has always been like this. We have been patching this by removing the PUMI libs in setup.py, but now that your stuff is in, we can't keep doing this

**Comment by zhang-alvin** [comment]
The header files should be coming from the `scorec` package in the PROTEUS_ARCH.yaml file:
https://github.com/hashdist/hashstack/blob/stable/proteus/examples/proteus.linux2.yaml#L92

Once the `scorec` package is compiled, the header files are automatically copied to the PROTEUS_ARCH/include directory.

**Comment by adimako** [comment]
https://github.com/HRWallingford/hashstack/blob/stable/hydra/gcc6.1.0/examples/proteus.centos.yaml

This is what we are using. The only difference is the `use:host-mpi `command. In the pkgs file, we use a different version of scorec 

```
sources:
  - url: https://github.com/tjcorona/core.git
key: git:374c1f0640d2a96242e7a5fd01fd27bd5a935b11
`````

**Comment by zhang-alvin** [comment]
The version of scorec shouldn't be an issue. @tridelat mentioned that the `use:host-mpi` was more of a hack to avoid compiling the `scorec` tools altogether as that redirects hashdist to unpackage the `host-mpi.yaml` file instead. I suggest removing that line. That should prompt the actual compilation of the `scorec` package and very likely, you'll run into an error regarding `zoltan` when you're compiling Proteus.

**Comment by adimako** [comment]
@zhang-alvin Correct, but what do I do with the zoltan error

**Comment by zhang-alvin** [comment]
If @cekees's update to the build stack does not work, I'd go ahead and remove the zoltan dependency. It's useful as a third-party graph partitioner, but the adaptivity tools should be able to function without it.

**Comment by adimako** [comment]
@cekees the patch does not work. @zhang-alvin if I remove the zoltan deps, then it compiles, but I get an mpi.h error (kinda makes sense, as we do not use host-mpi). If not, then I get the aph.h error. For now I have deactivated PUMI libs from NumericalSolution.py and setup.py, but we can't use the mesh adaptivity

**Comment by zhang-alvin** [comment]
When you removed the zoltan dependencies, did you make the following changes: https://github.com/zhang-alvin/hashstack/commit/c1d314bacd5687f67ec66b11ef03abcd316c8e41?

With these modifications, the `scorec` package should be able to compile without zoltan. Proteus should compile fine when #572 is merged in.

**Comment by adimako** [comment]
Yes. I still think it is an mpi library issue.

**Comment by adimako** [comment]
@zhang-alvin @cekees
 
- Nothing we tried so far works
- I do not think it is a good idea not to use host-mpi for hydra, 
- My understanding is that whilst scorec is built in the hashdist folder, include files and libs are not carried across to the PROTEUS_ARCH folder. 
- I do not feel that zoltan is an issue

**Comment by zhang-alvin** [comment]
Fix was merged in. Closing issue.
