### ISSUE TITLE
Tracking hashstack dependency more effectively

### ISSUE THREAD

**Issue by ahmadia** [erdc-cm/proteus#92]
Right now we don't automatically set the hashstack commit that we're using in any way.  The default behavior is to pull the latest commit on one of our tracking branch, and to commit this on builds.

One big issue is that when `make` is called in the future, there is no warning that a commit is possibly out of date.  There have been a few proposed ideas and solutions for this:

* Switch to .gitmodules for hashstack.  This still relies on the user checking that the proteus commit is up-to-date, but warns them when their hashstack commit is out-of-date.

* Add a .txt file that is manually updated by developers when they want to point to the most recent version of the repository.

* Switch from the in-repository profile format to an external repository profile format, such as https://github.com/hashdist/hashstack/blob/master/examples/mpi4py.linux.yaml

* Embed the hashstack repository into proteus branches, and put the maintenance work for communicating information between the repositories on developers comfortable with `git subtree` operations.

* Other ideas?

There are merits and cons to each approach.  I'm opening this issue just to get the discussion started.  I'll try to summarize discussion in this top-level comment, and we should use the comments for discussion.

**Comment by cekees** [comment]
refs to hashdist and hashstack commits are stored in .hashdist_default and .hashstack_default now.
